// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzPih9bAYpJvjWyB9GYkeRb0JiBs8yuEk',
    appId: '1:1078690064541:web:8f53363be78587e6620c74',
    messagingSenderId: '1078690064541',
    projectId: 'vrit-7c4d1',
    authDomain: 'vrit-7c4d1.firebaseapp.com',
    storageBucket: 'vrit-7c4d1.appspot.com',
    measurementId: 'G-PTEBGHPKKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBVUHDQJbZvxjSlyiHs8VoAXmFgzck7aA',
    appId: '1:1078690064541:android:1de3b6829da09100620c74',
    messagingSenderId: '1078690064541',
    projectId: 'vrit-7c4d1',
    storageBucket: 'vrit-7c4d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8vc470gfGSzdTvkbETdPbL5JNn3pzi-0',
    appId: '1:1078690064541:ios:ca46472bfb661fc3620c74',
    messagingSenderId: '1078690064541',
    projectId: 'vrit-7c4d1',
    storageBucket: 'vrit-7c4d1.appspot.com',
    androidClientId: '1078690064541-4s8og73q03du7pko84q1oh89vdtj3kvl.apps.googleusercontent.com',
    iosClientId: '1078690064541-mpafg1a7hrm5h16lvrcbpvnquss4fuol.apps.googleusercontent.com',
    iosBundleId: 'com.example.vrit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8vc470gfGSzdTvkbETdPbL5JNn3pzi-0',
    appId: '1:1078690064541:ios:ca46472bfb661fc3620c74',
    messagingSenderId: '1078690064541',
    projectId: 'vrit-7c4d1',
    storageBucket: 'vrit-7c4d1.appspot.com',
    androidClientId: '1078690064541-4s8og73q03du7pko84q1oh89vdtj3kvl.apps.googleusercontent.com',
    iosClientId: '1078690064541-mpafg1a7hrm5h16lvrcbpvnquss4fuol.apps.googleusercontent.com',
    iosBundleId: 'com.example.vrit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzPih9bAYpJvjWyB9GYkeRb0JiBs8yuEk',
    appId: '1:1078690064541:web:2bd90e7bf41ab366620c74',
    messagingSenderId: '1078690064541',
    projectId: 'vrit-7c4d1',
    authDomain: 'vrit-7c4d1.firebaseapp.com',
    storageBucket: 'vrit-7c4d1.appspot.com',
    measurementId: 'G-24W18VW00C',
  );
}
